# Generated by Django 4.1 on 2022-09-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Isbn', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100, unique=True)),
                ('editorial', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('no_page', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPrestamos.estudiante')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPrestamos.libro')),
            ],
        ),
    ]
