# Generated by Django 4.1 on 2022-09-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPrestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
